#- Jykell configuration

# markdown: redcarpet
markdown: kramdown
# highlighter: pygments
highlighter: rouge
paginate: 5
language: 'en-us'

#- Website information.
name: 'The Internet at the Speed of Light'
description: "Reducing latency to the physical limit is the next grand challenge for our interactive network experiences. How can we build a Speed-of-Light Internet?"

author: 'Team cSpeed'
#- Edit 'categories' in the front matter of every post
#-  to match this username.
# nickname: speedy
# bio: '...'
# location: '..'
# url: '...'
# image: 'assets/images/...'

# short_url: '...'
# google_analytics: ...
# disqus: <username>
baseurl: /cspeed.net/

#- Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


gems: [jekyll-paginate]
exclude: [vendor]

#- Additional settings available on the front-matter
#- Site logo in the index.html (as in demo.ghost.io)
#- Author's page cover in _layouts/author.html
#- The same for page.html and tag.html layouts
#- Post's page cover as a per-post basis _posts/...
#- Disqus comments as a per-post basis


#- Settings for deploy rake task
safe: false
lsi: false
#- Username and repository name in Github.
# username: <username>
#- `repo` defaults to USERNAME.github.io
# repo: <repository-name>
#- `branch` defaults to "source" for USERNAME.github.io
#-  or "master" otherwise
# branch: <master|...>
# relative_source: ../jasper/
destination: ./docs
# production_url: <...>
# source_url: <...>

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - Makefile
  - .envrc